### ISSUE TITLE
Initial release of basic version

### ISSUE THREAD

**Issue by tboerger** [owncloud/ocis-graph#7]
Just prepare an initial basic version to serve a graph world API that can be used by Phoenix or other extensions.

**Comment by DeepDiver1975** [comment]
## ToDos
- [x] integrate auth middleware + openid integration
- [x] properly return user data on /me endpoint
- [x] return users from ldap
- [x] return groups from ldap

**Comment by tboerger** [comment]
This issue isn't done, it's done when we got the first release tagged, which will be the case when it's clear that the single binary stuff is working as expected.

**Comment by butonic** [comment]
graph is part of the single binary ... yet it is still untagged ...
